### ISSUE TITLE
importlib.metadata.PackageNotFoundError: No package metadata was found for fit-to-tcx

### ISSUE THREAD

**Issue by christofferholmstedt** [Tigge/FIT-to-TCX#14]
(Kubuntu) Ubuntu 22.04.2 LTS

**Unable to get fittotcx parse fit files**
After some initial trouble with poetry (never used it before, so not sure if I used it properly) I run ```python3 -m fittotcx.program``` and get following error:

_fittotcx is never added to the path so the README information about just running ```fittotcx``` does not work, neither does the shell script._

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/<redacted>/files/40-49-repositories/41-products/FIT-to-TCX/fittotcx/program.py", line 307, in <module>
    sys.exit(main())
  File "/home/<redacted>/files/40-49-repositories/41-products/FIT-to-TCX/fittotcx/program.py", line 298, in main
    document = convert(args.file)
  File "/home/<redacted>/files/40-49-repositories/41-products/FIT-to-TCX/fittotcx/program.py", line 277, in convert
    add_author(document)
  File "/home/<redacted>/files/40-49-repositories/41-products/FIT-to-TCX/fittotcx/program.py", line 154, in add_author
    [version_major, version_minor] = importlib_metadata.version("fit-to-tcx").split(".")
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 984, in version
    return distribution(distribution_name).version
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 957, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for fit-to-tcx
```
**Some metadata missing**
I have searched for this issue and it seems that it is some kind of build metadata that is not properly set. Any hints which metadata needs to be added where is appreciated.

**Comment by christofferholmstedt** [comment]
I probably didn't do this correctly due to lack of python knowledge. I used poetry to build the distribution files ```poetry build``` (dist catalog created in the repository). Inside the build direcftory I ran ```sudo python3 -m pip install fit_to_tcx-0.2-py3-none-any.whl```.

The installation doesn't feel right, I assume python virtual environments could have been used somehow instead but I lack python knowledge to dig deeper into this. Now the fittotcx application is installed globally and available automatically in the path.
