### ISSUE TITLE
pkg_resources.DistributionNotFound: fit-to-tcx==0.1

### ISSUE THREAD

**Issue by pavlinux** [Tigge/FIT-to-TCX#7]
# fittotcx
Traceback (most recent call last):
  File "/usr/bin/fittotcx", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: fit-to-tcx==0.1

**Comment by Tigge** [comment]
Hi, what linux distribution and python version are you using? Some threads suggest this error might occur if mixing `easy_install` and `pip` -- not sure if that is the case here though.
